package model;
// Generated 8/03/2016 11:36:39 PM by Hibernate Tools 4.3.1



/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String numCuenta;
     private Usuario usuario;
     private String materia;
     private String escolaridad;

    public Estudiante() {
    }

	
    public Estudiante(String numCuenta, String materia, String escolaridad) {
        this.numCuenta = numCuenta;
        this.materia = materia;
        this.escolaridad = escolaridad;
    }
    public Estudiante(String numCuenta, Usuario usuario, String materia, String escolaridad) {
       this.numCuenta = numCuenta;
       this.usuario = usuario;
       this.materia = materia;
       this.escolaridad = escolaridad;
    }
   
    public String getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(String numCuenta) {
        this.numCuenta = numCuenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public String getEscolaridad() {
        return this.escolaridad;
    }
    
    public void setEscolaridad(String escolaridad) {
        this.escolaridad = escolaridad;
    }




}


