package model;
// Generated 8/03/2016 11:36:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String username;
     private String nombre;
     private String apellido;
     private String password;
     private String email;
     private Set estudiantes = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String username, String nombre, String apellido, String password, String email) {
        this.username = username;
        this.nombre = nombre;
        this.apellido = apellido;
        this.password = password;
        this.email = email;
    }
    public Usuario(String username, String nombre, String apellido, String password, String email, Set estudiantes) {
       this.username = username;
       this.nombre = nombre;
       this.apellido = apellido;
       this.password = password;
       this.email = email;
       this.estudiantes = estudiantes;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


